# Generated by Django 3.0 on 2020-01-17 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='hot_deals',
        ),
    ]
