# Generated by Django 3.0 on 2020-01-18 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200117_2342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='Product_image_thumb1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image1',
            new_name='Product_image_thumb2',
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image_thumb3',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='Product_image_thumb4',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image_big',
            field=models.ImageField(blank=True, null=True, upload_to='product'),
        ),
    ]
