# Generated by Django 3.0 on 2020-01-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Product_image_thumb1',
            new_name='product_image_thumb1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_image_thumb2',
            new_name='product_image_thumb2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_image_thumb3',
            new_name='product_image_thumb3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Product_image_thumb4',
            new_name='product_image_thumb4',
        ),
        migrations.AddField(
            model_name='product',
            name='specification1_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification2_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification3_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specification4_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
