# Generated by Django 3.0 on 2020-01-18 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20200118_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specification4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='specification4_title',
        ),
    ]
