# Generated by Django 3.0 on 2020-01-18 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image_big',
            new_name='image',
        ),
    ]
