# Generated by Django 3.0 on 2020-02-07 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200207_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured_products_description',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
