# Generated by Django 3.0 on 2020-04-02 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_auto_20200402_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_description',
            new_name='product_full_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_specification1',
            new_name='product_specification_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_specification2',
            new_name='product_specification_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_specification3',
            new_name='product_specification_3',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_specification1_title',
            new_name='title_of_product_specification_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_specification2_title',
            new_name='title_of_product_specification_2',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_specification3_title',
            new_name='title_of_product_specification_3',
        ),
    ]
