# Generated by Django 3.0 on 2020-04-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_auto_20200402_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_available',
            new_name='available',
        ),
    ]
