# Generated by Django 3.0 on 2020-04-02 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20200402_2138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_slug',
            new_name='slug',
        ),
    ]
