# Generated by Django 3.0 on 2020-04-02 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_auto_20200402_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_stock',
            new_name='stock',
        ),
    ]
