# Generated by Django 3.0 on 2020-04-02 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_auto_20200402_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_price',
            new_name='price',
        ),
    ]
