# Generated by Django 3.0 on 2021-02-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_remove_product_product_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title_of_product_specification_1',
            new_name='product_condition_1',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_of_product_specification_2',
            new_name='product_condition_10',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='title_of_product_specification_3',
            new_name='product_condition_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured_products_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_full_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_specification_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_specification_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_specification_3',
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_7',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_8',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_condition_9',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
